# Generated by Django 5.0.2 on 2025-12-20 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MajorIncident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                (
                    "incident_type",
                    models.CharField(
                        choices=[
                            ("EARTHQUAKE", "Earthquake"),
                            ("MISSILE_STRIKE", "Missile Strike"),
                            ("BUILDING_COLLAPSE", "Building Collapse"),
                            ("FLOOD", "Flood"),
                            ("HAZMAT", "HAZMAT"),
                            ("WILDFIRE", "Wildfire"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DECLARED", "Declared"),
                            ("ACTIVE", "Active"),
                            ("STABILIZING", "Stabilizing"),
                            ("RECOVERY", "Recovery"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("location_lat", models.FloatField()),
                ("location_lng", models.FloatField()),
                (
                    "radius_meters",
                    models.IntegerField(
                        default=5000, help_text="Estimated affected area radius"
                    ),
                ),
                ("estimated_casualties", models.IntegerField(default=0)),
                ("confirmed_deaths", models.IntegerField(default=0)),
                ("displaced_persons", models.IntegerField(default=0)),
                ("command_post_lat", models.FloatField(blank=True, null=True)),
                ("command_post_lng", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("declared_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="IncidentEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("STATUS_CHANGE", "Status Change"),
                            ("ASSIGNMENT", "Assignment"),
                            ("UPDATE", "Update"),
                            ("HAZARD_ALERT", "Hazard Alert"),
                            ("CASUALTY_UPDATE", "Casualty Update"),
                            ("EVACUATION", "Evacuation"),
                            ("RESOURCE_ARRIVAL", "Resource Arrival"),
                            ("COMMUNICATION", "Communication"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("INFO", "Informational"),
                            ("WARNING", "Warning"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="INFO",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("created_by", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "incident",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="api.incident",
                    ),
                ),
                (
                    "major_incident",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="api.majorincident",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Sector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("location_lat", models.FloatField()),
                ("location_lng", models.FloatField()),
                (
                    "hazard_level",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="MEDIUM",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active Response"),
                            ("CONTAINED", "Contained"),
                            ("CLEARED", "Cleared"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("hazard_description", models.CharField(blank=True, max_length=300)),
                ("estimated_survivors", models.IntegerField(default=0)),
                (
                    "access_status",
                    models.CharField(default="PARTIALLY_ACCESSIBLE", max_length=100),
                ),
                ("primary_responder", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "major_incident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sectors",
                        to="api.majorincident",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TaskGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("SEARCH_RESCUE", "Search & Rescue"),
                            ("EVACUATION", "Evacuation"),
                            ("MEDICAL", "Medical Response"),
                            ("UTILITIES", "Utilities/Infrastructure"),
                            ("SECURITY", "Security & Perimeter"),
                            ("LOGISTICS", "Logistics & Supply"),
                            ("DAMAGE_ASSESSMENT", "Damage Assessment"),
                            ("COMMUNICATIONS", "Communications"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLANNED", "Planned"),
                            ("IN_PROGRESS", "In Progress"),
                            ("PAUSED", "Paused"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="PLANNED",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="MEDIUM",
                        max_length=20,
                    ),
                ),
                (
                    "progress_percent",
                    models.IntegerField(default=0, help_text="0-100%"),
                ),
                ("assigned_units_count", models.IntegerField(default=0)),
                ("completed_subtasks", models.IntegerField(default=0)),
                ("total_subtasks", models.IntegerField(default=0)),
                ("commander_name", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "major_incident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_groups",
                        to="api.majorincident",
                    ),
                ),
                (
                    "sectors",
                    models.ManyToManyField(related_name="task_groups", to="api.sector"),
                ),
            ],
            options={
                "ordering": ["-priority", "-created_at"],
            },
        ),
    ]
