# Generated by Django 5.0.2 on 2026-05-19 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_majorincident_incidentevent_sector_taskgroup"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="incident",
            name="severity",
        ),
        migrations.AddField(
            model_name="incident",
            name="priority",
            field=models.CharField(
                choices=[
                    ("LOW", "Low"),
                    ("MED", "Medium"),
                    ("HIGH", "High"),
                    ("CRITICAL", "Critical"),
                ],
                default="LOW",
                max_length=10,
            ),
        ),
    ]
