# Generated by Django 5.0.2 on 2026-06-22 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_task_mock_unit_pushtoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="unit",
            name="is_online",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="unit",
            name="last_seen",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
