# Generated by Django 5.0.2 on 2026-06-22 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_unit_is_online_unit_last_seen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unit",
            name="is_online",
            field=models.BooleanField(default=True),
        ),
    ]
