# Generated by Django 5.0.2 on 2026-08-17 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_alter_task_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="incidentevent",
            name="actor_id",
            field=models.IntegerField(
                blank=True,
                help_text="ID of the authenticated user who performed this action, if any.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="incident",
            name="status",
            field=models.CharField(
                choices=[
                    ("OPEN", "Open"),
                    ("PENDING", "Pending"),
                    ("EN_ROUTE", "En Route"),
                    ("ON_SCENE", "On Scene"),
                    ("IN_PROGRESS", "In Progress"),
                    ("RESOLVED", "Resolved"),
                    ("CLOSED", "Closed"),
                ],
                default="OPEN",
                max_length=20,
            ),
        ),
    ]
