# Generated by Django 5.0.2 on 2026-08-17 11:05

from django.db import migrations, models


def reset_existing_units_offline(apps, schema_editor):
    """
    Pre-existing Unit rows may have is_online=True from the old default,
    even though none of them have ever been claimed by a real authenticated
    user (User.unit is a new link). Reset them so the "must not appear
    online unless a real user is attached" invariant holds for old data too.
    """
    Unit = apps.get_model("api", "Unit")
    Unit.objects.filter(is_online=True).update(is_online=False)


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_incidentevent_actor_id_alter_incident_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unit",
            name="is_online",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(reset_existing_units_offline, migrations.RunPython.noop),
    ]
