# Generated by Django 5.0.2 on 2026-08-19 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_alter_unit_is_online"),
    ]

    operations = [
        migrations.CreateModel(
            name="FieldCommand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "field_key",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
                ("name", models.CharField(max_length=200)),
                ("location_lat", models.FloatField(blank=True, null=True)),
                ("location_lng", models.FloatField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("CLOSED", "Closed")],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "incident_phase",
                    models.CharField(default="Containment", max_length=100),
                ),
                ("casualty_count", models.IntegerField(default=0)),
                ("evacuated_count", models.IntegerField(default=0)),
                ("unit_name", models.CharField(blank=True, default="", max_length=200)),
                (
                    "incident_type",
                    models.CharField(default="General Incident", max_length=100),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("closed_reason", models.TextField(blank=True, null=True)),
                (
                    "closed_by_role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("FIELD_OPERATOR", "Field Operator"),
                            ("COMMAND_CENTER", "Command Center"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "closed_by_name",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="incident",
            name="channel",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="incident",
            name="closed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="incident",
            name="closed_by",
            field=models.CharField(
                blank=True,
                choices=[("UNIT", "Unit"), ("COMMAND_CENTER", "Command Center")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="incident",
            name="closed_by_name",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
        migrations.AddField(
            model_name="incident",
            name="closed_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="incident",
            name="field_command",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="incidents",
                to="api.fieldcommand",
            ),
        ),
        migrations.AddField(
            model_name="unit",
            name="field_command",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="units",
                to="api.fieldcommand",
            ),
        ),
        migrations.CreateModel(
            name="FieldCommandNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "field_command",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="api.fieldcommand",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
