# Generated by Django 5.0.2 on 2026-08-21 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_fieldcommand_incident_channel_incident_closed_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="majorincident",
            name="incident",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="major_incident",
                to="api.incident",
            ),
        ),
        migrations.AlterField(
            model_name="sector",
            name="location_lat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sector",
            name="location_lng",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="Perimeter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "points",
                    models.JSONField(
                        help_text="Ordered list of {lat, lng} objects tracing the boundary."
                    ),
                ),
                (
                    "submitted_by_role",
                    models.CharField(
                        choices=[
                            ("FIELD_OPERATOR", "Field Operator"),
                            ("COMMAND_CENTER", "Command Center"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "major_incident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perimeters",
                        to="api.majorincident",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
