# Generated by Django 5.0.2 on 2026-08-21 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_majorincident_incident_alter_sector_location_lat_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="incidentevent",
            name="source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("COMMAND_CENTER", "Command Center"),
                    ("FIELD_OPERATOR", "Field Operator"),
                    ("UNIT", "Unit"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
