# Generated by Django 5.0.2 on 2026-08-24 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_incidentevent_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="fieldcommand",
            name="major_incident",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="field_commands",
                to="api.majorincident",
            ),
        ),
    ]
