# Generated by Django 5.0.2 on 2026-08-24 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_fieldcommand_major_incident"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="fieldcommand",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("major_incident__isnull", False), ("status", "ACTIVE")
                ),
                fields=("major_incident",),
                name="unique_active_major_incident_link",
            ),
        ),
    ]
