# Generated by Django 5.0.2 on 2026-08-27 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_fieldcommand_unique_active_major_incident_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldcommandnote',
            name='kind',
            field=models.CharField(choices=[('NOTE', 'Note'), ('INCIDENT_LINKED', 'Incident Linked'), ('FORCE_ASSIGNED', 'Force Assigned'), ('MISSION', 'Mission'), ('STATUS', 'Status Change')], default='NOTE', max_length=20),
        ),
        migrations.CreateModel(
            name='FieldCommandMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('details', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('DONE', 'Done')], default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_missions', to='api.unit')),
                ('field_command', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='api.fieldcommand')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
