# Generated by Django 5.0.2 on 2026-08-30 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_fieldcommandnote_kind_fieldcommandmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentevent',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='api.task'),
        ),
    ]
