# Generated by Django 5.0.2 on 2026-09-01 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_merge_mobile_dispatch_mirror_incidents'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='arrived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
