# Generated by Django 5.0.2 on 2026-09-01 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_task_arrived_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldcommandmission',
            name='force_type',
            field=models.CharField(blank=True, choices=[('POLICE', 'Police'), ('FIRE', 'Fire'), ('MEDICAL', 'Medical')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='fieldcommandmission',
            name='incident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_tasks', to='api.incident'),
        ),
    ]
