# Generated by Django 5.0.2 on 2026-09-01 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_fieldcommandmission_force_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentFigureReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_by', models.CharField(blank=True, max_length=150)),
                ('injured', models.PositiveIntegerField(default=0)),
                ('dead', models.PositiveIntegerField(default=0)),
                ('trapped', models.PositiveIntegerField(default=0)),
                ('treated', models.PositiveIntegerField(default=0)),
                ('evacuated', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='figure_reports', to='api.incident')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='figure_reports', to='api.unit')),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('incident', 'unit')},
            },
        ),
    ]
