# Generated by Django 5.0.2 on 2026-09-02 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_incidentfigurereport'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldcommandnote',
            name='incident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_command_notes', to='api.incident'),
        ),
    ]
