# Generated by Django 5.0.2 on 2026-09-02 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_backfill_and_prune_field_command_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldcommandmission',
            name='incident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='field_tasks', to='api.incident'),
        ),
        migrations.AlterField(
            model_name='fieldcommandnote',
            name='incident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='field_command_notes', to='api.incident'),
        ),
    ]
